{{- if .Values.ingress.enabled -}}
{{- $ingressName := include "f5cisingressv2.ingressname" . -}}
{{- $serviceName := .Values.service.serviceName -}}
{{- $vsIp := .Values.ingress.annotations.virtualserverip -}}
{{- $vsPort := .Values.ingress.annotations.virtualserverhttpport -}}
{{- $vsPartition := .Values.ingress.annotations.partition -}}
{{- $vsBalance := .Values.ingress.annotations.balance -}}
{{- $vsHealth := .Values.ingress.annotations.health -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    {{- include "f5cisingressv2.labels" . | nindent 4 }}
  annotations:
    virtual-server.f5.com/ip: "{{ $vsIp }}"
    virtual-server.f5.com/http-port: "{{ $vsPort }}"
    virtual-server.f5.com/partition: "{{ $vsPartition }}"
    virtual-server.f5.com/balance: "{{ $vsBalance }}"
    virtual-server.f5.com/health: "{{ $vsHealth }}"
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.host }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts.path }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $svcPort }}
{{- end }}
